### ISSUE TITLE
Question: Is it possible to get an IOSurface backed CVPixelBuffer from a PIX?

### ISSUE THREAD

**Issue by f0rr0** [antonheestand/PixelKit#16]
What I am trying to achieve is the following:

Use the CameraPix and remove background (green screen), blend it with a custom background, get IOSurface backed CVPixelBuffer from the resultant PIX and publish them to an external process.

**Comment by antonheestand** [comment]
I’ve been trying to get IOSurface backed textures without luck unfortunatly.
